config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :documents do
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end
  end
  resources :documents

  root 'documents#index'

end

app/models/ability.rb
#Ability
class Ability
  include CanCan::Ability
  # Define abilities for the passed in user.
  def initialize(user)
    # Handle the case where we don't have a current_user i.e. the user is a guest
    user ||= User.new
    can :read, :all
    can :create, Document
    can :update, Document do |document|
      document.try(:user) == user
    end
    can :destroy, Document do |document|
      document.try(:user) == user
    end
  end
end

app/models/document.rb
#Document
class Document < ActiveRecord::Base
  belongs_to :user

  has_paper_trail

  # ensure that a user_id is present
  validates :user_id, presence: true
  # ensure that title is present and unique
  validates :title, presence: true, uniqueness: true
  # ensure that content is present
  validates :content, presence: true

  #return the documents wich contain the searched word
  def self.search(search)
    where("content LIKE ?", "%#{search}%")
  end

  #return the occurences of a word in all documents
  #it's case insensitive
  def self.count_occurences(key)
    re = /<("[^"]*"|'[^']*'|[^'">])*>/
    result = Hash.new(0)
    Document.all.find_each do |document|
      document.content.split.each do |word|
        word = word.gsub(re, '')
        result[key] += 1 if word.downcase == key.downcase
      end
    end
    result[key]
  end
end

app/models/user.rb
#User
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :documents, dependent: :destroy
end

app/controllers/application_controller.rb
#ApplicationController
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/documents_controller.rb
#DocumentsController
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /documents
  # GET /documents.json
  def index
    @other_documents = Document.where.not(user_id: current_user.id)
                              .paginate(page: params[:others_page], per_page: 7)
    @user_documents = Document.where(user_id: current_user.id)
                              .paginate(page: params[:user_page], per_page: 7)
    if params[:search]
      @document_results = Document.search(params[:search])
                                  .paginate(page: params[:page], per_page: 7)
      @occurences = Document.count_occurences(params[:search])
    else
      @document_results = @other_documents
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id
    @document.save
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def document_params
    params.require(:document).permit(:title, :content, :user_id)
  end
end

app/controllers/versions_controller.rb
#VersionsController
class VersionsController < ApplicationController
  before_action :set_document_and_version, only: [:diff, :rollback, :destroy]

  #show the modifications of a document
  def diff
  end

  # change the current document to the specified version
  # reify gives you the object of this version
  def rollback
    document = @version.reify
    document.save
    redirect_to edit_document_path(document)
  end

  private

  #return the desired version of a document
  def set_document_and_version
    @document = Document.find(params[:document_id])
    @version = @document.versions.find(params[:id])
  end
end

app/helpers/application_helper.rb
#ApplicationHelper
module ApplicationHelper
  #boostrap style messages
  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  #renders falsh messages
  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
#DeviseHelper
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/documents_helper.rb
#DocumentsHelper
module DocumentsHelper
  #compares old content with actual content of a document
  def diff(content1, content2)
    changes = Diffy::Diff.new(content1, content2,
                              include_plus_and_minus_in_html: true,
                              include_diff_info: true)
    changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end
end

app/views/documents/_edit.html.haml
.modal-header
  %h3.center= "Editing #{@document.title}"
  .editable
  :javascript
    var editor = new MediumEditor('.edit');
  = render 'simpleform'

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
  - if @document.errors.any?
    #error_explanation
      %h2
        = pluralize(@document.errors.count, "error")
        prohibited this document from being saved:
      %ul
        - @document.errors.full_messages.each do |message|
          %li= message
  .field
    = f.input :title,class: "form-control"
  .field
    = f.label :content
    %br/
    = f.text_area :content, class: "form-control", rows: "20"
  .actions
    = f.button :submit, class: "btn btn-primary"

app/views/documents/_new.html.haml
.modal-header
  %h3.center New Document
  :javascript
    var editor = new MediumEditor('.edit');
= render 'simpleform'

app/views/documents/_save.js.erb
$("ul.errors").html("")
<% if @document.errors.any? %>
  <% @document.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#document-modal").modal("hide")
<% end %>

app/views/documents/_search_results.html.haml
.col-xs-offset-1.col-sm-10.col-md-10
  %table.table
    %thead
      %tr
        %th
        %th Title
        %th Owner
    %h3.center Results
    %tbody
      - @document_results.each do |document|
        %tr
          %td= image_tag  "document.png", width: '32'
          %td= document.title
          %td= document.user.email
          %td= link_to 'View', document, class: :"btn btn-sm btn-default"
          %td= link_to 'Edit',edit_document_path(document), class: :"btn btn-sm btn-default" if can? :update, document
          %td= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' }, class: :"btn btn-sm btn-danger" if can? :destroy, document
  .ol-sm-offset-3.col-md-offset-3
    = will_paginate @document_results

app/views/documents/_show.html.haml
.modal-header
  .modal-dialog
    .modal-content
      .modal-body
        -# .col-md-4.col-md-offset-4.pull-right
          -# %form
          -#   .form-group
          -#     %input#search.form-control{:placeholder => "Search", :type => "text"}/
        %p
          %strong Title:
          = @document.title
        %div#document_content
          %strong Content:
          = @document.content.html_safe
      .modal-footer
        - if can? :update, @document
          = link_to 'Edit', edit_document_path(@document), remote: true, class: "space btn btn-primary"
        = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}

app/views/documents/_simpleform.html.haml
.modal-dialog
  .modal-content
    = simple_form_for @document, remote: true do |f|
      .modal-body
        %ul.errors
        .field
          = f.input :title,class: "form-control"
        .field
          = f.input :content, as: :contenteditable, input_html: {class: "shared-class edit"}, contenteditable_html: {class: "div-only-class"}
      .modal-footer
        .actions
          = f.button :submit, class: "btn btn-primary"
          = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}
    = render 'documents/versions', document: @document

app/views/documents/create.js.erb
<%= render "save" %>

app/views/documents/edit.js.erb
$("#document-modal").html("<%= escape_javascript(render 'edit') %>")
$("#document-modal").modal("show")

app/views/documents/index.html.haml
.container-fluid
  .row
    - if @document_results.present?
      - if params[:search] != nil
        %p.result
          Found #{@occurences} occurences of "
          %i>= params[:search]
          "
        = render :partial => 'search_results'
      - else
        .col-sm-6.col-md-6
          .panel.panel-default
            .panel-heading.center Other Documents
            %table.table
              %tbody
                - @other_documents.each do |document|
                  %tr
                    %td= image_tag  "document.png", width: '32'
                    %td= document.title
                    %td= document.user.email
                    %td= link_to 'View ', document, remote: true, class: :"btn btn-sm btn-default"
            .col-sm-offset-3.col-md-offset-3
              = will_paginate @other_documents, param_name: :others_page
        .col-sm-6.col-md-6
          .panel.panel-default
            .panel-heading.center My Documents
            %table.table
              %tbody
                - @user_documents.each do |document|
                  %tr
                    %td= image_tag  "document.png", width: '32'
                    %td= document.title
                    %td= link_to 'View', document, remote: true, class: :"btn btn-sm btn-default"
                    %td= link_to 'Edit',edit_document_path(document), remote: true, class: :"btn btn-sm btn-default" if can? :update, document
                    %td= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' }, class: :"btn btn-sm btn-danger" if can? :destroy, document

            .col-sm-offset-3.col-md-offset-3.col-xs-offset-3
              = will_paginate @user_documents, param_name: :user_page
    - else
      %p.result
        There are no documents containing the term(s) #{params[:search]}.

app/views/documents/new.js.erb
$("#document-modal").html("<%= escape_javascript(render 'new') %>")
$("#document-modal").modal("show")

app/views/documents/show.js.erb
$("#document-modal").html("<%= escape_javascript(render 'show') %>")
$("#document-modal").modal("show")

app/views/documents/update.js.erb
<%= render "save" %>

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    MANI-doc - A basic Document Management System
  %nav

app/views/layouts/_header.html.haml
%body
  %header
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a
            = link_to "MANI-DOC", root_path,class:"navbar-brand"
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Dashboard', root_path, class:"navbar-link"
            %li.new= link_to 'New Document', new_document_path, remote: true, class:"navbar-link"
          %p.navbar-user.pull-right
            - if user_signed_in?
              = succeed " - " do
                %strong= current_user.email
              = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
            - else
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ManiDOC
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render(:partial => 'layouts/header')
    = flash_messages
    = yield
    = render 'layouts/footer'
#document-modal.modal.fade

app/views/versions/diff.html.haml
.container-fluid
  .row
    .col-md-8.col-md-offset-2
      .row.mt
        .col-sm-12
          %h2= "Diff between Version #{@version.id} and Current Version"
          :css
            #{Diffy::CSS}
          .well.diff
            %p
              %strong Title:
              = diff(@version.reify.title, @document.title)
            %p
              %strong Content:
              = diff(@version.reify.content, @document.content)
      .fr
        = link_to 'Back', edit_document_path(@document), class: 'btn btn-default'
        = link_to 'Undo', rollback_document_version_path(@document, @version), class: 'btn btn-primary', method: 'PATCH'